name: Compile and Release

on:
  push:
    paths:
      - 'manifest.json'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y zip

    - name: Package Extension to CRX
      run: |
        zip -r ThottaThukiduven.crx . -x "*.git*" "release/*"
        mkdir -p release
        rm -f release/ThottaThukiduven.crx
        mv ThottaThukiduven.crx release/

    - name: Commit and Push CRX to Repository
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add release/ThottaThukiduven.crx
        git commit -m "Update ThottaThukiduven.crx"
        git push

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: New release of the extension.
        draft: false
        prerelease: false

    - name: Upload CRX to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release/ThottaThukiduven.crx
        asset_name: ThottaThukiduven.crx
        asset_content_type: application/x-chrome-extension
        
