name: Compile and Release

on:
  push:
    paths:
      - 'manifest.json'
      
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y zip jq

    - name: Extract Version from manifest.json
      run: |
        echo "VERSION=$(jq -r .version manifest.json)" >> $GITHUB_ENV

    - name: Package Extension to CRX
      run: |
        zip -r ThottaThukiduven.crx . -x "*.git*" ".github/releases/*"
        mkdir -p .github/releases
        rm -f .github/releases/ThottaThukiduven.crx
        mv ThottaThukiduven.crx .github/releases/

    - name: Generate updates.xml
      run: |
        cat <<EOF > .github/releases/updates.xml
        <?xml version="1.0" encoding="UTF-8"?>
        <gupdate xmlns="http://www.google.com/update2/response" protocol="2.0">
          <app appid="YOUR_EXTENSION_ID">
            <updatecheck codebase="https://github.com/sr2echa/ThottaThukiduven/raw/main/.github/releases/ThottaThukiduven.crx" version="$VERSION" />
          </app>
        </gupdate>
        EOF

    - name: Commit and Push CRX and updates.xml to Repository
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .github/releases/ThottaThukiduven.crx .github/releases/updates.xml
        git commit -m "Update ThottaThukiduven.crx and updates.xml"
        git push

    - name: Create GitHub Release
      id: create_release
      uses: gh-actions/create-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ env.VERSION }}
        release_name: Release v${{ env.VERSION }}
        body: New release of the extension.
        draft: false
        prerelease: false

    - name: Upload CRX to Release
      uses: gh-actions/upload-release-asset@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./.github/releases/ThottaThukiduven.crx
        asset_name: ThottaThukiduven.crx
        asset_content_type: application/x-chrome-extension
